### PR TITLE
chore: yarn workspaces, release please

### PR DESCRIPTION
**Pull request by mpetrunic**
**Motivation**

**Description**

Closes #issue_number

**Steps to test or reproduce**

### CODE REVIEW

**Comment by wemeetagain** [comment]
Do we need to add a GITHUB_TOKEN? or will the one auto-injected be ok?

**Comment by dapplion** [comment]
Why there's a 26,767 line diff in the yarn.lock?

**Comment by mpetrunic** [comment]
> Why there's a 26,767 line diff in the yarn.lock?

Upgrade to new yarn version and format of the lockfile

**Comment by mpetrunic** [comment]
> Do we need to add a GITHUB_TOKEN? or will the one auto-injected be ok?

Autoinjected is fine

**Review by dapplion — DISMISSED** [review]

**Comment by wemeetagain** [comment]
@ChainSafe/lodestar
After this is merged, you'll need to run `corepack enable` to properly use the correct version of `yarn` here.
See https://nodejs.org/api/corepack.html

**Review by wemeetagain — APPROVED** [review]

**Pull request merged**
