### PR TITLE
feat/snapshot-eip-4881

### PR DESCRIPTION
**Pull request by AkshatGada**
Attempts to solve issue https://github.com/ChainSafe/lodestar/issues/4935
1. Added deposit contract snapshot interface 
2.  Added test cases

waiting for your review

### CODE REVIEW

**Comment by philknows** [comment]
If you were trying to [commit your work from here](https://github.com/AkshatGada/Snapshot-lodestar/commits/main/), it did not make it into this PR...

**Review by wemeetagain — COMMENTED** [review]
Looks like a good start. A few comments:

Instead of redefining MerkleTree, Leaf, Node, etc here, please reuse the existing infra from this library. That means using the existing `Tree`, `LeafNode`, `BranchNode` constructs. You should be able to define your custom tree editing / navigation functions either purely functionally, or in a wrapper class.

Eventually, this code / PR should be migrated to the lodestar repo and live there. Whether you want to keep this review here for now is up to you.

**Comment by AkshatGada** [comment]
Thanks so much for your feedback , I will start resolving the linting
errors and also start to run successfully tests .
Regards ,
Akshat

**Comment by philknows** [comment]
Hi @AkshatGada , do you still plan to keep working on this?

**Comment by AkshatGada** [comment]
Yes , I am  a little busy with college and my internship , I am running tests locally , please grant me some time to get it done .

**Comment by AkshatGada** [comment]
I am planning to do it as a project for the ethereum protocol fellowship.

**Comment by philknows** [comment]
Superseded by #400

**Pull request closed without merging**
