### PR TITLE
fix: add hasher alias to webpack config to fix build

### PR DESCRIPTION
**Pull request by nflaig**
**Motivation**

Closes https://github.com/ChainSafe/ssz/issues/324

**Description**

Add alias to webpack config to fix build.

@g11tech I noticed you [added this](https://github.com/ChainSafe/ssz/compare/a7548d9b9fc5ed4315eaca8aebb8db4970e48c7e..c57882e2383e17399bed01e02512631d2f13e55a) in https://github.com/ChainSafe/ssz/pull/318 but it got removed by  a force-push.

### CODE REVIEW

**Comment by nflaig** [comment]
looks like this fixes it locally for me but breaks it in CI, must be missing something else

**Review by g11tech — APPROVED** [review]
lgtm, although aliasing shouldn't be required anymore (or that was the aim)

**Comment by nflaig** [comment]
@g11tech yeah, looking at https://github.com/ethereumjs/ethereumjs-monorepo/pull/2656, seems to be working fine by removing aliases. The build only fails for me locally, CI works as expected. Are you able to build locally? I must be missing something

**Comment by g11tech** [comment]
i have figured out what is happening, old cached node modules of previous versions are still interfering 

1. Remove all node_modules ( main repo root `node_modules` as well as  inside `packages/*/node_modules` If you had old code, their previous builds are cached there and are interfering)
2. `corepack enable` if you haven't been running it to enable yarn workspace functionality

then 
1. `yarn --immutable` for installing packages
2. `yarn build`

then the build is successful

**Pull request closed without merging**
